import streamlit as st
import pandas as pd
import pickle
from math import radians, sin, cos, sqrt, atan2
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb
import streamlit as st
import numpy as np
import joblib

# ------------------------------
# LOAD MODEL + LABEL ENCODERS
# ------------------------------
model = joblib.load("xgboost_model.pkl")

# Load dictionary of label encoders
label_encoders = joblib.load("label_encoders.pkl")

# Extract each encoder
le_merchant = label_encoders["merchant"]
le_job = label_encoders["job"]
le_category = label_encoders["category"]
le_gender = label_encoders["gender"]

# ------------------------------
# STREAMLIT UI
# ------------------------------
st.title(" Credit Card Fraud Detection App")
st.write("Fill in the transaction details to predict fraud.")

merchant = st.selectbox("Merchant",['fraud_Doyle Ltd', 'fraud_Hammes-Beatty', 'fraud_Streich Ltd',
       'fraud_Heller, Gutmann and Zieme', 'fraud_Terry Ltd',
       'fraud_Kihn-Fritsch', 'fraud_Lang, Towne and Schuppe',
       'fraud_Satterfield-Lowe', 'fraud_Witting, Beer and Ernser',
       'fraud_Gulgowski LLC', 'fraud_Leannon-Ward', 'fraud_Padberg-Sauer',
       'fraud_Schmidt and Sons', 'fraud_Botsford Ltd',
       'fraud_Ledner-Pfannerstill', 'fraud_Hagenes, Kohler and Hoppe',
       'fraud_Christiansen, Goyette and Schamberger',
       'fraud_Mayert Group', 'fraud_Stiedemann Ltd',
       'fraud_Turcotte, Batz and Buckridge',
       'fraud_Robel, Cummerata and Prosacco', 'fraud_Waters-Cruickshank',
       'fraud_Dare, Casper and Bartoletti', "fraud_O'Keefe-Hudson",
       'fraud_Kihn Inc', 'fraud_Bahringer, Schoen and Corkery',
       'fraud_Ferry, Reichel and DuBuque', 'fraud_Lockman Ltd',
       'fraud_Beier LLC', 'fraud_Ebert-Daugherty',
       'fraud_Champlin-Casper', 'fraud_Jewess LLC',
       'fraud_Wisozk and Sons', 'fraud_Auer LLC',
       'fraud_Spencer-Runolfsson', 'fraud_Bins, Balistreri and Beatty',
       'fraud_Denesik, Powlowski and Pouros', 'fraud_Reynolds-Schinner',
       'fraud_Bernhard Inc', 'fraud_Cummings LLC',
       'fraud_Langworth, Boehm and Gulgowski', 'fraud_Nienow PLC',
       'fraud_Fritsch and Sons', 'fraud_Nader-Maggio',
       'fraud_Quitzon-Goyette', 'fraud_Tillman, Fritsch and Schmitt',
       'fraud_Pouros-Conroy', 'fraud_Walter, Hettinger and Kessler',
       'fraud_Torphy-Goyette', 'fraud_Reinger, Weissnat and Strosin',
       'fraud_Zieme, Bode and Dooley', 'fraud_Herzog Ltd',
       'fraud_Ernser-Lynch', 'fraud_Vandervort-Funk',
       'fraud_Wuckert-Walter', 'fraud_Luettgen PLC',
       'fraud_Dibbert and Sons', 'fraud_Willms, Kris and Bergnaum',
       'fraud_Yost-Rogahn', 'fraud_Kuphal-Toy', 'fraud_Kirlin and Sons',
       'fraud_Schoen-Quigley', 'fraud_Goyette Inc', 'fraud_Kuvalis Ltd',
       'fraud_McKenzie-Huels', 'fraud_Hills, Hegmann and Schaefer',
       'fraud_Schaefer, Fay and Hilll', 'fraud_Murray-Smitham',
       'fraud_Gerlach Inc', 'fraud_Erdman-Kertzmann',
       'fraud_Gislason Group', 'fraud_Paucek-Wiza', 'fraud_Hills-Boyer',
       'fraud_Effertz LLC', 'fraud_Langworth LLC',
       'fraud_Altenwerth, Cartwright and Koss', 'fraud_Bahringer-Streich',
       'fraud_Connelly, Reichert and Fritsch',
       'fraud_Kutch, Hermiston and Farrell', 'fraud_Haag-Blanda',
       'fraud_Rempel Inc', 'fraud_Gaylord-Powlowski', 'fraud_Zboncak Ltd',
       'fraud_Raynor, Feest and Miller', 'fraud_Cartwright-Harris',
       'fraud_Bauch-Raynor', 'fraud_Klein Group',
       'fraud_Jenkins, Hauck and Friesen', 'fraud_Schmitt Ltd',
       'fraud_Haley Group', 'fraud_Brekke and Sons', 'fraud_Bednar PLC',
       'fraud_Kilback LLC', 'fraud_Bins-Tillman', 'fraud_Williamson LLC',
       "fraud_Greenholt, O'Hara and Balistreri", 'fraud_Kutch and Sons',
       'fraud_Shields Inc', 'fraud_Spinka Inc',
       'fraud_Altenwerth-Kilback', 'fraud_Lynch-Mohr',
       'fraud_Watsica LLC', 'fraud_Cole PLC', 'fraud_Schaefer Ltd',
       'fraud_Connelly-Carter', 'fraud_Thiel Ltd', 'fraud_Wiegand-Lowe',
       'fraud_Bradtke PLC', 'fraud_Beier-Hyatt', 'fraud_Pacocha-Weissnat',
       'fraud_Sporer Inc', 'fraud_McDermott, Osinski and Morar',
       'fraud_Schoen, Kuphal and Nitzsche',
       'fraud_Schumm, Bauch and Ondricka',
       'fraud_Kling, Howe and Schneider', 'fraud_Parker-Kunde',
       'fraud_Maggio-Fahey', 'fraud_Schiller, Blanda and Johnson',
       'fraud_Kassulke Inc', 'fraud_Erdman-Ebert',
       'fraud_Weimann-Lockman', 'fraud_Howe PLC', 'fraud_Dare-Gibson',
       'fraud_Wolf Inc', 'fraud_Romaguera Ltd', 'fraud_Miller-Harris',
       'fraud_Swift, Bradtke and Marquardt',
       'fraud_Schmeler, Bashirian and Price', 'fraud_Towne LLC',
       'fraud_Conroy Ltd', 'fraud_Metz-Boehm',
       'fraud_Streich, Hansen and Veum',
       'fraud_Conroy, Balistreri and Gorczany',
       'fraud_Okuneva, Schneider and Rau',
       'fraud_Reilly, Heaney and Cole', 'fraud_Yost, Block and Koepp',
       'fraud_Rau and Sons', 'fraud_Hoppe, Harris and Bednar',
       'fraud_Kulas Group', 'fraud_Watsica, Haag and Considine',
       'fraud_Bechtelar-Rippin', 'fraud_Fadel-Hilpert',
       'fraud_Wuckert, Wintheiser and Friesen',
       'fraud_Kohler, Lindgren and Koelpin', 'fraud_Durgan-Auer',
       'fraud_Kihn-Schuster', 'fraud_Heathcote, Yost and Kertzmann',
       'fraud_Torphy-Kertzmann', 'fraud_Reichert, Huels and Hoppe',
       'fraud_Cartwright PLC', 'fraud_Swaniawski, Lowe and Robel',
       'fraud_Hodkiewicz, Prohaska and Paucek', 'fraud_Kemmer-Buckridge',
       'fraud_Wilkinson Ltd', 'fraud_Block-Parisian',
       'fraud_Parker, Nolan and Trantow', 'fraud_Grimes LLC',
       'fraud_Labadie, Treutel and Bode', 'fraud_Hudson-Grady',
       'fraud_Schumm PLC', 'fraud_Harris Inc', 'fraud_Abernathy and Sons',
       'fraud_Weber, Thiel and Hammes',
       'fraud_Stokes, Christiansen and Sipes', 'fraud_Smitham-Boehm',
       'fraud_Emard Inc', 'fraud_Runolfsdottir, Mueller and Hand',
       'fraud_Kautzer and Sons', 'fraud_Connelly PLC',
       'fraud_Bahringer Group', 'fraud_Turner, Ruecker and Parisian',
       'fraud_Bins-Rice', 'fraud_Schiller Ltd', 'fraud_Crooks and Sons',
       'fraud_Collier LLC', 'fraud_Weber and Sons', 'fraud_Waelchi Inc',
       'fraud_Barton Inc', 'fraud_Feil-Morar', 'fraud_Rau-Grant',
       'fraud_Nienow, Ankunding and Collier', 'fraud_Monahan-Morar',
       'fraud_Prohaska-Murray', 'fraud_Rowe-Vandervort',
       'fraud_Lehner, Reichert and Mills', 'fraud_Schmidt-Larkin',
       'fraud_Parisian and Sons', 'fraud_Roob LLC',
       'fraud_Streich, Dietrich and Barton', 'fraud_Nader-Heller',
       'fraud_Kris-Padberg', 'fraud_Collier Inc', 'fraud_Jakubowski Inc',
       'fraud_Romaguera, Cruickshank and Greenholt',
       'fraud_Bahringer, Bergnaum and Quitzon', "fraud_Friesen-D'Amore",
       'fraud_Turner and Sons', 'fraud_Klocko LLC',
       'fraud_Koss, McLaughlin and Mayer', 'fraud_Medhurst Inc',
       'fraud_Kovacek Ltd', 'fraud_Schumm, McLaughlin and Carter',
       'fraud_Lowe, Dietrich and Erdman', 'fraud_Conroy-Emard',
       'fraud_Kutch Group', 'fraud_Goyette, Howell and Collier',
       'fraud_Kutch-Ferry', 'fraud_Koepp-Witting',
       'fraud_Osinski, Ledner and Leuschke', "fraud_Schamberger-O'Keefe",
       'fraud_Kilback Group', 'fraud_Ernser-Feest', 'fraud_Wiza LLC',
       'fraud_Lesch Ltd', 'fraud_Bahringer, Osinski and Block',
       'fraud_Fadel, Mertz and Rippin', 'fraud_Heller PLC',
       'fraud_Hamill-Daugherty', 'fraud_Ziemann-Waters',
       'fraud_Upton PLC', 'fraud_Strosin-Cruickshank',
       'fraud_Sporer-Keebler', 'fraud_Bogisich Inc',
       'fraud_Schaefer, Maggio and Daugherty', 'fraud_Goodwin-Nitzsche',
       'fraud_Koepp-Parker', 'fraud_Bauch-Blanda',
       'fraud_Parisian, Schiller and Altenwerth', 'fraud_Kutch-Wilderman',
       'fraud_Botsford PLC', 'fraud_Goyette-Gerhold',
       'fraud_Rolfson-Kunde', 'fraud_Greenholt, Jacobi and Gleason',
       "fraud_O'Hara-Wilderman", 'fraud_Jacobi and Sons',
       'fraud_Yost, Schamberger and Windler', 'fraud_Huels-Nolan',
       'fraud_Ledner, Hartmann and Feest', 'fraud_Dibbert-Green',
       'fraud_Wiza, Schaden and Stark', 'fraud_Koelpin and Sons',
       'fraud_Hirthe-Beier', 'fraud_Berge-Ullrich',
       "fraud_O'Connell, Botsford and Hand",
       'fraud_Lehner, Mosciski and King',
       'fraud_Moore, Williamson and Emmerich',
       'fraud_Schroeder, Wolff and Hermiston', 'fraud_Cruickshank-Mills',
       'fraud_Kiehn-Emmerich', 'fraud_Becker, Harris and Harvey',
       'fraud_Schmitt Inc', 'fraud_Kuhn Group', 'fraud_Skiles LLC',
       'fraud_Hudson-Ratke', 'fraud_Volkman-Predovic',
       'fraud_Ruecker-Mayert', 'fraud_Sawayn PLC', 'fraud_Marks Inc',
       'fraud_Jerde-Hermann', 'fraud_McDermott-Rice',
       'fraud_Rutherford, Homenick and Bergstrom', 'fraud_Dickinson Ltd',
       'fraud_Barrows PLC', 'fraud_Durgan, Gislason and Spencer',
       "fraud_O'Keefe-Wisoky", 'fraud_Bartoletti-Wunsch',
       'fraud_Schultz, Simonis and Little', 'fraud_Brown PLC',
       'fraud_Hackett-Lueilwitz', 'fraud_Kilback and Sons',
       'fraud_Hayes, Marquardt and Dibbert', 'fraud_McCullough LLC',
       'fraud_Botsford and Sons', 'fraud_Thompson-Gleason',
       'fraud_Pollich LLC', 'fraud_Kunze Inc',
       'fraud_Schroeder, Hauck and Treutel',
       'fraud_Terry, Johns and Bins', 'fraud_Kub PLC',
       'fraud_Bogisich-Homenick', 'fraud_Ritchie, Bradtke and Stiedemann',
       'fraud_Hills-Witting', 'fraud_Stoltenberg-Beatty',
       'fraud_Zemlak, Tillman and Cremin', 'fraud_Stamm-Witting',
       'fraud_Tromp Group', 'fraud_Eichmann-Kilback',
       'fraud_Reilly and Sons', 'fraud_Cummings Group',
       'fraud_Armstrong, Walter and Gottlieb', 'fraud_Zulauf LLC',
       'fraud_Haley, Jewess and Bechtelar', 'fraud_Torp-Labadie',
       'fraud_Kiehn Inc', 'fraud_Daugherty, Pouros and Beahan',
       'fraud_Pouros, Walker and Spencer', 'fraud_White and Sons',
       'fraud_Stiedemann Inc', 'fraud_Hermiston, Russel and Price',
       'fraud_Flatley-Durgan', 'fraud_Reichel Inc', 'fraud_Renner Ltd',
       'fraud_Kutch LLC', 'fraud_Friesen-Stamm',
       'fraud_Larkin, Stracke and Greenfelder', 'fraud_Bode-Schuster',
       'fraud_Windler LLC', 'fraud_Schneider, Hayes and Nikolaus',
       'fraud_Fisher Inc', 'fraud_Towne, Greenholt and Koepp',
       'fraud_Wilkinson LLC', 'fraud_Gutmann-Upton', 'fraud_Berge-Hills',
       'fraud_Nolan-Williamson', 'fraud_Labadie LLC',
       'fraud_Roberts-Beahan', 'fraud_Schoen, Nienow and Bauch',
       'fraud_Emmerich-Rau', 'fraud_Jakubowski Group',
       'fraud_Gottlieb, Considine and Schultz', 'fraud_Tillman LLC',
       'fraud_Hahn, Bahringer and McLaughlin', 'fraud_Marvin-Lind',
       'fraud_Simonis-Prohaska', 'fraud_Turcotte-Halvorson',
       'fraud_Morissette PLC', 'fraud_Runolfsson and Sons',
       'fraud_Cormier LLC', 'fraud_Mosciski Group', 'fraud_Baumbach Ltd',
       'fraud_Windler, Goodwin and Kovacek', 'fraud_Will Ltd',
       "fraud_Hamill-D'Amore", 'fraud_Wintheiser, Dietrich and Schimmel',
       'fraud_Eichmann, Hayes and Treutel', 'fraud_Fadel Inc',
       'fraud_Metz, Russel and Metz', 'fraud_Fisher-Schowalter',
       'fraud_Douglas, Schneider and Turner',
       'fraud_Berge, Kautzer and Harris',
       'fraud_Roberts, Daniel and Macejkovic', 'fraud_Mohr-Bayer',
       'fraud_Rau-Robel', 'fraud_Kerluke PLC', 'fraud_Boyer PLC',
       'fraud_Treutel-King', 'fraud_Nienow, Barrows and Romaguera',
       'fraud_Gerhold LLC', 'fraud_Welch Inc',
       'fraud_Schuppe, Nolan and Hoeger', 'fraud_Jast-McDermott',
       'fraud_Casper, Hand and Zulauf', 'fraud_Buckridge PLC',
       'fraud_Little, Gutmann and Lynch',
       'fraud_Kihn, Abernathy and Douglas', 'fraud_Bahringer-Larson',
       'fraud_Crist, Jakubowski and Littel', 'fraud_Koss and Sons',
       'fraud_Abbott-Rogahn', 'fraud_Weimann, Kuhic and Beahan',
       'fraud_Kuphal-Bartoletti', 'fraud_Turcotte, McKenzie and Koss',
       'fraud_Greenfelder, Bartoletti and Davis',
       'fraud_Stanton, Jakubowski and Baumbach',
       'fraud_Roberts, Ryan and Smith',
       'fraud_Mosciski, Gislason and Mertz', 'fraud_Greenholt Ltd',
       'fraud_Gottlieb-Hansen', 'fraud_Osinski Inc',
       'fraud_Erdman-Schaden', 'fraud_Harber Inc',
       'fraud_Baumbach, Strosin and Nicolas', 'fraud_Morissette LLC',
       'fraud_Heller-Langosh', 'fraud_Denesik and Sons',
       'fraud_Ullrich Ltd', 'fraud_Romaguera, Wehner and Tromp',
       'fraud_Abbott-Steuber', 'fraud_Heathcote LLC',
       'fraud_Boehm, Predovic and Reinger',
       'fraud_Lockman, West and Runte',
       'fraud_Schaefer, McGlynn and Bosco',
       'fraud_Effertz, Welch and Schowalter',
       'fraud_Bernier, Volkman and Hoeger', 'fraud_Brown Inc',
       'fraud_Jacobi Inc', 'fraud_Welch, Rath and Koepp',
       'fraud_Hintz, Bauch and Smith', 'fraud_Friesen Inc',
       'fraud_Hettinger, McCullough and Fay', 'fraud_Wilkinson PLC',
       'fraud_Rippin-VonRueden', 'fraud_Kuhn LLC', 'fraud_Lemke-Gutmann',
       'fraud_Barton LLC', 'fraud_Swift PLC',
       'fraud_Kilback, Nitzsche and Leffler', 'fraud_Donnelly LLC',
       'fraud_Cummerata-Jones', 'fraud_Macejkovic-Lesch',
       'fraud_Stehr, Jewess and Schimmel', 'fraud_Erdman-Durgan',
       'fraud_Dare-Marvin', 'fraud_Mueller, Gerhold and Mueller',
       'fraud_Mosciski, Ziemann and Farrell', 'fraud_Kuphal-Predovic',
       'fraud_Powlowski-Weimann', 'fraud_Reichel LLC',
       'fraud_Douglas-White', 'fraud_Pacocha-Bauch',
       'fraud_Rodriguez Group', 'fraud_Kassulke PLC',
       'fraud_Padberg-Welch', 'fraud_Kutch, Steuber and Gerhold',
       'fraud_Lakin, Ferry and Beatty', 'fraud_Kuhic Inc',
       'fraud_Nicolas, Hills and McGlynn',
       'fraud_Reichert, Rowe and Mraz', 'fraud_Larkin Ltd',
       'fraud_Emmerich-Luettgen', 'fraud_Dicki Ltd',
       'fraud_Bernier and Sons', 'fraud_Bode-Rempel',
       'fraud_Baumbach, Feeney and Morar', 'fraud_Howe Ltd',
       'fraud_Swaniawski, Nitzsche and Welch',
       'fraud_Towne, Walker and Borer', 'fraud_Olson, Becker and Koch',
       'fraud_Ankunding LLC', 'fraud_Jast Ltd',
       'fraud_Goldner, Kovacek and Abbott', 'fraud_Thiel-Thiel',
       'fraud_Lubowitz, Terry and Stracke', 'fraud_Ruecker Group',
       'fraud_Waelchi-Wolf', 'fraud_Adams, Kovacek and Kuhlman',
       'fraud_Cremin, Hamill and Reichel',
       'fraud_Hartmann, Rowe and Hermann', 'fraud_Gibson-Deckow',
       'fraud_Monahan, Hermann and Johns',
       'fraud_Bradtke, Torp and Bahringer', 'fraud_Bogisich-Weimann',
       'fraud_Stroman, Hudson and Erdman', 'fraud_Huels-Hahn',
       'fraud_Bashirian Group', "fraud_Deckow-O'Conner",
       'fraud_Jast and Sons', 'fraud_Brown-Greenholt',
       'fraud_Boehm, Block and Jakubowski', 'fraud_Flatley Group',
       'fraud_Little Ltd', 'fraud_Tromp, Kerluke and Glover',
       'fraud_Kerluke Inc', "fraud_Pacocha-O'Reilly",
       'fraud_Gleason-Macejkovic', 'fraud_Prosacco, Kreiger and Kovacek',
       'fraud_Lind, Huel and McClure', 'fraud_Pouros-Haag',
       'fraud_Ruecker, Beer and Collier', 'fraud_Volkman PLC',
       'fraud_Cole, Hills and Jewess', 'fraud_Bernhard-Lesch',
       'fraud_DuBuque LLC', 'fraud_Feil, Hilpert and Koss',
       'fraud_Shields-Wunsch', 'fraud_Conroy-Cruickshank',
       "fraud_O'Connell-Ullrich", 'fraud_Hermann and Sons',
       'fraud_Schuppe-Schuppe', 'fraud_Langosh, Wintheiser and Hyatt',
       'fraud_Balistreri-Nader', 'fraud_Kessler Inc', 'fraud_Dooley Inc',
       'fraud_Hyatt, Russel and Gleichner', 'fraud_Rippin, Kub and Mann',
       'fraud_Herman, Treutel and Dickens',
       'fraud_Kunze, Larkin and Mayert',
       'fraud_McCullough, Hudson and Schuster', 'fraud_Trantow PLC',
       'fraud_Kovacek, Dibbert and Ondricka', 'fraud_Dooley-Thompson',
       'fraud_Quitzon, Green and Bashirian', 'fraud_Crona and Sons',
       'fraud_Christiansen-Gusikowski', 'fraud_Eichmann-Russel',
       'fraud_Stark-Koss', 'fraud_Smith-Stokes', 'fraud_Carroll PLC',
       'fraud_Abshire PLC', 'fraud_Gutmann Ltd',
       "fraud_O'Reilly, Mohr and Purdy",
       'fraud_Bernhard, Grant and Langworth', 'fraud_Graham and Sons',
       'fraud_Heaney-Marquardt', 'fraud_Fritsch LLC',
       'fraud_Leffler-Goldner', 'fraud_Lynch Ltd', 'fraud_Schulist Ltd',
       'fraud_Dach-Borer', 'fraud_Daugherty-Thompson',
       'fraud_Spencer PLC', 'fraud_Zboncak, Rowe and Murazik',
       'fraud_Boyer-Reichert', 'fraud_Schimmel-Olson',
       'fraud_Lubowitz-Walter', 'fraud_Kuhic, Bins and Pfeffer',
       'fraud_Gleason and Sons', 'fraud_Morar Inc',
       'fraud_Hilpert-Conroy', 'fraud_Turner, Ziemann and Lehner',
       'fraud_Hoppe-Parisian', 'fraud_Huel, Hammes and Witting',
       'fraud_Hickle Group', 'fraud_Baumbach, Hodkiewicz and Walsh',
       'fraud_Beer-Jast', 'fraud_Volkman Ltd', 'fraud_Berge LLC',
       'fraud_Haley, Batz and Auer', 'fraud_Mraz-Herzog',
       'fraud_Huel-Langworth', 'fraud_Goyette-Herzog', 'fraud_Herman Inc',
       'fraud_Kozey-Kuhlman', 'fraud_Gottlieb Group', 'fraud_Johns Inc',
       'fraud_Kertzmann LLC', 'fraud_McDermott-Weimann',
       'fraud_Halvorson Group', 'fraud_Predovic Inc',
       'fraud_Kerluke, Kertzmann and Wiza', 'fraud_Jaskolski-Dibbert',
       'fraud_Reilly LLC', 'fraud_Kerluke, Considine and Macejkovic',
       'fraud_Schuppe LLC', 'fraud_Bailey-Morar',
       'fraud_Cronin, Kshlerin and Weber', 'fraud_Miller-Hauck',
       'fraud_Murray Ltd', 'fraud_Terry-Huel', 'fraud_Kemmer-Reinger',
       'fraud_Zboncak LLC', 'fraud_Graham, Hegmann and Hammes',
       'fraud_Jones, Sawayn and Romaguera', 'fraud_Hermann-Gaylord',
       'fraud_Rodriguez, Yost and Jenkins',
       'fraud_Moen, Reinger and Murphy',
       'fraud_Gutmann, McLaughlin and Wiza',
       'fraud_Torp, Muller and Borer', 'fraud_Pfeffer LLC',
       'fraud_Adams-Barrows', 'fraud_Moore, Dibbert and Koepp',
       'fraud_Kozey-Boehm', 'fraud_Wuckert-Goldner',
       'fraud_Ratke and Sons', 'fraud_Bartoletti and Sons',
       'fraud_Pfeffer and Sons',
       'fraud_Konopelski, Schneider and Hartmann',
       'fraud_Stamm-Rodriguez', 'fraud_Medhurst, Cartwright and Ebert',
       'fraud_Medhurst, Labadie and Gottlieb', 'fraud_Corwin-Collins',
       'fraud_Dare, Fritsch and Zboncak', 'fraud_Kozey-McDermott',
       'fraud_McGlynn-Jaskolski', 'fraud_Schroeder Group',
       'fraud_Dickinson-Rempel', 'fraud_Heidenreich PLC',
       'fraud_Goldner-Lemke', 'fraud_Prosacco LLC', 'fraud_Friesen-Ortiz',
       'fraud_Hyatt-Blick', 'fraud_Medhurst PLC',
       'fraud_Roob, Conn and Tremblay',
       'fraud_Nitzsche, Kessler and Wolff',
       'fraud_Swaniawski, Bahringer and Ledner', 'fraud_Spinka-Welch',
       'fraud_Ortiz Group', 'fraud_Brown, Homenick and Lesch',
       'fraud_Beier and Sons', 'fraud_Douglas, DuBuque and McKenzie',
       'fraud_Friesen Ltd', 'fraud_Runte-Mohr', 'fraud_Pagac LLC',
       'fraud_Mante, Luettgen and Hackett', 'fraud_Little-Gleichner',
       'fraud_Schmeler Inc', 'fraud_Reichert, Shanahan and Hayes',
       'fraud_McGlynn-Heathcote', 'fraud_Jaskolski-Vandervort',
       'fraud_Kihn, Brakus and Goyette', "fraud_Lesch, D'Amore and Brown",
       'fraud_Funk Group', 'fraud_Cormier, Stracke and Thiel',
       'fraud_Kris-Weimann', 'fraud_Breitenberg LLC',
       'fraud_VonRueden Group', 'fraud_Reichel, Bradtke and Blanda',
       'fraud_Dietrich-Fadel', 'fraud_Kutch-Hegmann', 'fraud_Kuhic LLC',
       'fraud_Tillman, Dickinson and Labadie', 'fraud_Lynch-Wisozk',
       'fraud_Hermiston, Pacocha and Smith', 'fraud_Champlin and Sons',
       'fraud_Streich, Rolfson and Wilderman', 'fraud_Frami Group',
       'fraud_Johnson, Runolfsdottir and Mayer', 'fraud_Torp-Lemke',
       'fraud_Block Group', 'fraud_Stark-Batz', 'fraud_Fahey Inc',
       'fraud_Block-Hauck', 'fraud_Kub-Heaney', 'fraud_Kerluke-Abshire',
       'fraud_McCullough Group', 'fraud_Price Inc',
       'fraud_Rowe, Batz and Goodwin', 'fraud_Thiel PLC',
       'fraud_Shanahan-Lehner', 'fraud_Lind-Buckridge',
       'fraud_Skiles-Ankunding', 'fraud_Hagenes, Hermann and Stroman',
       'fraud_Rutherford-Mertz', 'fraud_Bins-Howell',
       'fraud_Bednar Group', 'fraud_Daugherty LLC',
       'fraud_Morissette, Weber and Wiegand',
       'fraud_Koss, Hansen and Lueilwitz', 'fraud_Kris-Kertzmann',
       'fraud_Hackett Group', 'fraud_Eichmann, Bogan and Rodriguez',
       'fraud_Mante Group', 'fraud_Breitenberg-Hermiston',
       'fraud_Donnelly PLC', 'fraud_Zemlak Group', 'fraud_Kling Inc',
       'fraud_Stracke-Lemke', 'fraud_Roob-Okuneva',
       'fraud_Romaguera and Sons', 'fraud_Kunde-Sanford',
       'fraud_Mohr Inc', 'fraud_Bruen-Yost', 'fraud_Schmeler-Howe',
       'fraud_Cummerata-Hilpert',
       'fraud_Klocko, Runolfsdottir and Breitenberg',
       'fraud_Raynor, Reinger and Hagenes', 'fraud_Deckow-Dare',
       'fraud_Rohan, White and Aufderhar', 'fraud_Kling-Ernser',
       'fraud_Lebsack and Sons', 'fraud_Schoen Ltd',
       'fraud_Kessler Group', 'fraud_Hahn, Douglas and Schowalter',
       'fraud_Homenick LLC', 'fraud_Corwin-Romaguera',
       'fraud_Corwin-Gorczany', 'fraud_Ritchie, Oberbrunner and Cremin',
       'fraud_Ferry, Lynch and Kautzer', 'fraud_Keeling-Crist',
       'fraud_Larson, Quitzon and Spencer', 'fraud_Boyer-Haley',
       'fraud_Morissette-Schaefer',
       'fraud_Champlin, Rolfson and Connelly', 'fraud_Huel Ltd',
       'fraud_Turner LLC', 'fraud_Johnston, Nikolaus and Maggio',
       'fraud_Runte, Green and Emard',
       'fraud_Bernier, Streich and Jewess', 'fraud_Larson-Moen',
       'fraud_Hills-Olson', 'fraud_Hauck, Dietrich and Funk',
       'fraud_Harris Group', 'fraud_Johnston-Casper',
       'fraud_Harris, Gusikowski and Heaney', 'fraud_Auer-Mosciski',
       'fraud_Johns-Hoeger', 'fraud_McLaughlin, Armstrong and Koepp',
       'fraud_Rempel PLC', 'fraud_Veum-Koelpin',
       'fraud_Reichert-Weissnat', 'fraud_Ankunding-Carroll',
       'fraud_Kling-Grant', 'fraud_Leannon-Nikolaus',
       'fraud_Cassin-Harvey', 'fraud_Bednar Inc', 'fraud_Heller-Abshire',
       'fraud_Dach-Nader', 'fraud_Padberg-Rogahn', 'fraud_Hintz-Bruen',
       'fraud_Auer-West', 'fraud_Monahan, Bogisich and Ledner',
       'fraud_Smitham-Schiller', 'fraud_Lemke and Sons'])

category = st.selectbox("Category", ['grocery_pos', 'kids_pets', 'home', 'food_dining', 'travel',
       'shopping_net', 'shopping_pos', 'gas_transport', 'health_fitness',
       'grocery_net', 'entertainment', 'misc_pos', 'personal_care',
       'misc_net'])
amt = st.number_input("Transaction Amount", min_value=0.0)

gender = st.selectbox("Gender", ["Male", "Female"])

lat = st.number_input("Customer Latitude")
long = st.number_input("Customer Longitude")

job = st.selectbox("Job Title",['Art gallery manager', 'Systems analyst',
       'Control and instrumentation engineer', 'Landscape architect',
       'Trading standards officer', 'Herbalist', 'Therapist, drama',
       'Futures trader', 'Cytogeneticist', 'Herpetologist',
       'Environmental consultant', 'Management consultant',
       'Associate Professor', 'Investment banker, corporate',
       'Research scientist (physical sciences)', 'Immunologist',
       'Surveyor, land/geomatics', 'Physiotherapist',
       'Pensions consultant', 'Chiropodist', 'IT trainer',
       'Maintenance engineer', 'Diagnostic radiographer',
       'Sports development officer', 'Clinical research associate',
       'Systems developer', 'Geoscientist',
       'Chartered public finance accountant', 'Dealer', 'Town planner',
       'Furniture conservator/restorer', 'Production engineer',
       'Geologist, engineering', 'Professor Emeritus', 'Economist',
       'Music tutor', 'Engineer, electronics', 'Counselling psychologist',
       'Tax adviser', 'Press photographer', 'Facilities manager',
       'Chief Executive Officer', 'Mining engineer',
       'Licensed conveyancer', 'Mechanical engineer',
       'Exhibitions officer, museum/gallery', 'Fitness centre manager',
       'Copywriter, advertising', 'Race relations officer',
       'Hospital doctor', 'Contractor', 'Clothing/textile technologist',
       'Surveyor, minerals', 'Financial trader', 'Energy engineer',
       'Telecommunications researcher', 'Accountant, chartered certified',
       'Claims inspector/assessor', 'Film/video editor',
       'Sales professional, IT', 'Doctor, hospital', 'Petroleum engineer',
       'Pharmacist, hospital', 'Health service manager',
       'Ceramics designer', 'Buyer, industrial',
       'Teacher, special educational needs', 'Radio producer',
       'Cartographer', 'Radiographer, therapeutic',
       'Horticulturist, commercial', 'Physiological scientist',
       'Clinical biochemist', 'Magazine features editor',
       'Editor, magazine features', 'Land/geomatics surveyor',
       'Archaeologist', 'Web designer', 'Education officer, museum',
       'Press sub', 'Chief Strategy Officer',
       'Advertising account planner', 'Editor, commissioning',
       'Designer, exhibition/display', 'Soil scientist',
       'Industrial/product designer', 'Scientist, research (maths)',
       'Producer, radio', 'Tourist information centre manager',
       'Phytotherapist', 'Social researcher',
       'Special educational needs teacher', 'Make', 'Heritage manager',
       'Operations geologist', 'Health visitor', 'Psychologist, forensic',
       'Firefighter', 'Radio broadcast assistant',
       'Accounting technician', 'Museum/gallery exhibitions officer',
       'Civil engineer, contracting', 'Patent attorney',
       'Designer, interior/spatial', 'Psychotherapist',
       'Chemical engineer', 'Librarian, academic',
       'Educational psychologist', 'Scientific laboratory technician',
       'Scientist, audiological', 'Museum education officer',
       'Glass blower/designer', 'Research scientist (maths)', 'Musician',
       'Teacher, early years/pre', 'Designer, jewellery',
       'Call centre manager', 'Materials engineer', 'Animal technologist',
       'Broadcast presenter', 'Insurance broker', 'Art therapist',
       'Engineer, communications', 'Exercise physiologist',
       'Public affairs consultant',
       'Scientist, research (physical sciences)', 'Trade mark attorney',
       'Careers information officer', 'Designer, ceramics/pottery',
       'Electrical engineer', 'Product designer', 'Theatre director',
       'Psychologist, sport and exercise', 'Site engineer',
       'Advertising copywriter', 'Market researcher',
       'Nutritional therapist', 'Financial adviser', 'Theme park manager',
       'Engineer, automotive', 'Programmer, multimedia',
       'Insurance risk surveyor', 'Administrator, arts',
       'Programme researcher, broadcasting/film/video',
       'Historic buildings inspector/conservation officer',
       'Teacher, secondary school', 'Psychotherapist, child',
       'Medical secretary', 'Health and safety adviser', 'Pilot, airline',
       'Water engineer', 'Engineer, biomedical',
       'Research officer, political party', 'Therapist, music',
       'Camera operator', 'Operational researcher',
       'Secondary school teacher', 'Lexicographer',
       'Corporate investment banker', 'Doctor, general practice',
       'Therapist, occupational', 'Paediatric nurse',
       'Public house manager', 'Research officer, trade union',
       "Barrister's clerk", 'Surveyor, rural practice',
       'Development worker, community', 'Biomedical scientist',
       'Audiological scientist', 'Advice worker',
       'Armed forces training and education officer', 'Barista',
       'Naval architect', 'Occupational psychologist',
       'Transport planner', 'Administrator, local government',
       'Electronics engineer', 'Charity fundraiser',
       'Psychologist, clinical', 'Oceanographer', 'Scientist, biomedical',
       'Librarian, public', 'Forensic psychologist',
       'Radiographer, diagnostic', 'Civil Service fast streamer',
       'Event organiser', 'Media planner', 'Garment/textile technologist',
       'Fine artist', 'Public relations account executive',
       'Drilling engineer', 'Architect', 'Child psychotherapist',
       'Research scientist (life sciences)', 'Early years teacher',
       'Engineer, control and instrumentation',
       'Lecturer, further education', 'Records manager',
       'Chartered accountant', 'Prison officer',
       'Interior and spatial designer', 'Pharmacologist',
       'Physicist, medical', 'Fisheries officer',
       'Commercial/residential surveyor', 'Designer, furniture',
       'Arboriculturist', 'Jewellery designer',
       'Waste management officer', 'Tree surgeon', 'Seismic interpreter',
       'Arts development officer', "Politician's assistant",
       'General practice doctor', 'Video editor',
       'Higher education careers adviser', 'Freight forwarder',
       'Engineer, civil (contracting)', 'Building control surveyor',
       'Comptroller', 'Teaching laboratory technician',
       'Amenity horticulturist', 'Further education lecturer',
       'Armed forces logistics/support/administrative officer',
       'Multimedia programmer',
       'Conservation officer, historic buildings', 'Toxicologist', 'Sub',
       'Ecologist', 'Agricultural consultant',
       'Senior tax professional/tax inspector', 'Applications developer',
       'Pathologist', 'Chief Financial Officer', 'Magazine journalist',
       'Civil Service administrator', 'Commissioning editor',
       'Podiatrist', 'Television/film/video producer', 'IT consultant',
       'Engineer, land', 'Travel agency manager',
       'Health promotion specialist', 'Private music teacher',
       'Accountant, chartered public finance', 'Engineer, maintenance',
       'Academic librarian', 'Engineer, building services',
       'Quarry manager', 'Theatre manager',
       'Geophysicist/field seismologist', 'Metallurgist',
       'Television floor manager', 'Presenter, broadcasting',
       'Production manager', 'Animator', 'Administrator, education',
       'Intelligence analyst', 'Scientist, marine', 'Medical physicist',
       'Exhibition designer', 'Structural engineer',
       'Commercial horticulturist', 'Biomedical engineer',
       'Learning disability nurse', 'Osteopath',
       'Development worker, international aid', 'Cabin crew',
       'Embryologist, clinical', 'Science writer', 'Colour technologist',
       'Building services engineer', 'Database administrator',
       'Counsellor', 'Bookseller', 'Scientist, physiological',
       'Learning mentor', 'Illustrator', 'Farm manager',
       'Communications engineer', 'Engineer, petroleum',
       "Nurse, children's", 'Television production assistant',
       'Risk analyst', 'Designer, textile', 'Health physicist',
       'Secretary/administrator', 'Editor, film/video',
       'Building surveyor', 'Regulatory affairs officer',
       'Research scientist (medical)', 'Engineer, drilling',
       'Rural practice surveyor', 'Administrator', 'Field seismologist',
       'Equities trader', 'Airline pilot', 'Company secretary',
       'Barrister', 'Aid worker', 'Stage manager',
       'Leisure centre manager', 'Chief Technology Officer',
       'Community pharmacist', 'Psychologist, counselling',
       'Programmer, applications', 'Equality and diversity officer',
       'Product/process development scientist', 'Animal nutritionist',
       'Chief Operating Officer', 'Producer, television/film/video',
       'Mental health nurse', 'Television camera operator',
       'Neurosurgeon', 'Environmental education officer',
       'Music therapist', 'Chartered legal executive (England and Wales)',
       'Medical technical officer', 'Copy',
       'Planning and development surveyor',
       'Medical sales representative', 'Architectural technologist',
       'Hospital pharmacist', 'Insurance claims handler',
       'Engineer, aeronautical', 'Investment analyst',
       'Designer, multimedia', 'Clinical psychologist',
       'Logistics and distribution manager', 'Pharmacist, community',
       'Engineer, technical sales', 'Solicitor, Scotland', 'Media buyer',
       'Chief of Staff', 'Community arts worker', 'Furniture designer',
       'Pension scheme manager', 'Insurance underwriter',
       'Manufacturing systems engineer', 'Community education officer',
       'English as a second language teacher', 'Geologist, wellsite',
       'Quantity surveyor', 'Aeronautical engineer', 'Product manager',
       'Statistician', 'Special effects artist',
       'Social research officer, government', 'Manufacturing engineer',
       'TEFL teacher', 'Lecturer, higher education', 'Broadcast engineer',
       'Police officer', 'Loss adjuster, chartered',
       'Teacher, primary school', 'Gaffer', 'Primary school teacher',
       'English as a foreign language teacher', 'Immigration officer',
       'Engineer, structural', 'Retail buyer', 'Surgeon', 'Retail banker',
       'Retail merchandiser', 'Probation officer',
       'Dance movement psychotherapist', 'Land',
       'Chartered loss adjuster', 'Horticultural therapist',
       'Conservator, museum/gallery', 'Technical brewer',
       'Nurse, mental health', 'Chemist, analytical',
       'Production assistant, radio', 'Therapist, art',
       'Engineering geologist', 'Engineer, production',
       'Community development worker', 'Tourism officer',
       'Education administrator', 'Tax inspector', 'Network engineer',
       'Scientist, research (medical)', 'Therapist, sports',
       'Energy manager', 'Sales executive', 'Wellsite geologist',
       'Paramedic', 'Museum/gallery conservator',
       'Occupational therapist', 'Curator',
       'Teacher, English as a foreign language',
       'Scientist, clinical (histocompatibility and immunogenetics)',
       'Public librarian', 'Dispensing optician',
       'Human resources officer', 'Outdoor activities/education manager',
       'Purchasing manager', 'Information systems manager',
       'Sport and exercise psychologist', 'Engineer, agricultural',
       'Mudlogger', 'Advertising account executive',
       'Sports administrator', 'Occupational hygienist',
       'Plant breeder/geneticist', 'Psychiatric nurse',
       'Administrator, charities/voluntary organisations', 'Hydrologist',
       'Orthoptist', 'Ambulance person', 'Retail manager',
       'Emergency planning/management officer', 'Buyer, retail',
       'Visual merchandiser', 'Restaurant manager, fast food',
       'Geochemist', 'Set designer', 'Optician, dispensing',
       'Designer, industrial/product', 'Hydrogeologist',
       'Surveyor, mining', 'Local government officer',
       'Air traffic controller', 'Engineer, mining', 'Location manager',
       'Engineer, broadcasting (operations)', 'Interpreter',
       'Estate manager/land agent', 'Data scientist',
       'Geneticist, molecular', 'Therapist, horticultural',
       'Warden/ranger', 'Psychiatrist', 'Public relations officer',
       'Horticultural consultant', 'Chief Marketing Officer',
       'Hotel manager', 'Environmental health practitioner',
       'Journalist, newspaper', 'Broadcast journalist',
       'Engineer, civil (consulting)', 'Artist', 'Lawyer',
       'Surveyor, hydrographic', 'Air broker', 'Teacher, adult education',
       'Biochemist, clinical', 'Merchandiser, retail',
       'Training and development officer',
       'Investment banker, operational', 'Engineer, materials',
       'Analytical chemist', 'Designer, television/film set',
       'Water quality scientist', 'Marketing executive',
       'Clinical cytogeneticist', 'Nature conservation officer',
       'Minerals surveyor', 'Tour manager', 'Engineer, manufacturing',
       'Charity officer', 'Field trials officer', 'Homeopath',
       'Volunteer coordinator', 'Production assistant, television',
       'Oncologist', 'Archivist', 'Optometrist', 'Acupuncturist',
       'Education officer, community', 'Hydrographic surveyor',
       'Conservator, furniture', 'Writer', 'Textile designer',
       'Engineer, site', 'Ship broker', 'Veterinary surgeon', 'Dancer',
       'Accountant, chartered', 'Sales promotion account executive',
       'Air cabin crew', 'Warehouse manager', 'Solicitor',
       'Environmental manager', 'Catering manager', 'Legal secretary',
       'Armed forces technical officer', 'Personnel officer',
       'Forest/woodland manager', 'Information officer',
       'Careers adviser', 'Industrial buyer',
       'Contracting civil engineer'])


merch_lat = st.number_input("Merchant Latitude")
merch_long = st.number_input("Merchant Longitude")

# year = st.number_input("Year", min_value=2000, max_value=2100)
# month = st.number_input("Month", min_value=1, max_value=12)
# day = st.number_input("Day", min_value=1, max_value=31)

# hour = st.number_input("Hour", min_value=0, max_value=23)
# day_of_week = st.number_input("Day of Week (0=Mon … 6=Sun)", min_value=0, max_value=6)

age = st.number_input("Age", min_value=0, max_value=120)

# ------------------------------
# SAFE ENCODING FUNCTION
# ------------------------------
def safe_encode(encoder, value):
    """Encode value using LabelEncoder. 
    If unseen value appears, return -1."""
    try:
        return encoder.transform([value])[0]
    except:
        return -1

# ------------------------------
# APPLY LABEL ENCODING
# ------------------------------
merchant_enc = safe_encode(le_merchant, merchant)
category_enc = safe_encode(le_category, category)
gender_enc = safe_encode(le_gender, gender)
job_enc = safe_encode(le_job, job)

# ------------------------------
# PREPARE INPUT FOR MODEL
# ------------------------------
input_data = np.array([[
    merchant_enc,
    category_enc,
    amt,
    gender_enc,
    lat,
    long,
    job_enc,
    merch_lat,
    merch_long,
    age
]])

# ------------------------------
# PREDICT BUTTON
# ------------------------------
if st.button("Predict Fraud"):
    prediction = model.predict(input_data)

    if prediction[0] == 1:
        st.error(" Fraud Detected!")
    else:
        st.success(" Transaction is Safe!")
